"""user-todo relationship

Revision ID: f59e02aeec8e
Revises: cb1ee7a7a120
Create Date: 2026-02-25 10:37:39.429179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59e02aeec8e'
down_revision = 'cb1ee7a7a120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_user_id", 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_id", type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
